kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: <name>
spec:
   accessModes:
      - ReadWriteOnce
   resources:
      requests:
         storage: <x>Gi
   storageClassName: <Storage Class>