---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: my-snapshot
spec:
  volumeSnapshotClassName: nutanix-volume-snapshot-class
  source:
    persistentVolumeClaimName: my-pvc
