---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: my-pvc
spec:
 dataSource:
   name: my-snapshot
   kind: VolumeSnapshot
   apiGroup: snapshot.storage.k8s.io
 accessModes:
   - ReadWriteOnce
 resources:
   requests:
     storage: 6Gi
